<?php
	require_once('functions/enqueue-styles-scripts.php');
	require_once('functions/customizer.php');
	require_once('functions/custom-walker.php');
	require_once('functions/gravity-forms.php');
	require_once('functions/register-menus.php');	
	require_once('functions/register-sidebars.php');
	require_once('functions/theme-setup.php');
	require_once('functions/woocommerce.php');
?>